# planner_interface.py

import subprocess
import os
from typing import List, Optional

import yaml
import logging

# Load configuration from YAML
try:
    with open('config.yaml', 'r', encoding='utf-8') as f:
        CONFIG = yaml.safe_load(f)
except Exception as e:
    raise RuntimeError("Failed to load configuration from 'config.yaml'.") from e

class PlannerInterface:
    """
    Interface to invoke a classical PDDL planner (e.g., FastDownward).
    Provides methods to run planning and check plan existence.
    """
    def __init__(self, planner_path: Optional[str] = None):
        """
        Initializes the planner interface.
        Args:
            planner_path (Optional[str]): Path to the planner executable.
                Defaults from config.yaml if None.
        """
        self.planner_path = planner_path or CONFIG.get('planner_path', None)
        if self.planner_path is None:
            raise ValueError("Planner path must be specified in config.yaml or as argument.")
        if not os.path.isfile(self.planner_path):
            raise FileNotFoundError(f"Planner executable not found at: {self.planner_path}")
        # Folder to store temporary plan files
        self._plan_filename = 'temp_plan.txt'
        # Setup logger
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.INFO)

    def run_planner(self, domain_filepath: str, problem_filepath: str, timeout: int = 300) -> Optional[List[str]]:
        """
        Executes the planner on given domain and problem files.
        Args:
            domain_filepath (str): Path to domain PDDL file.
            problem_filepath (str): Path to problem PDDL file.
            timeout (int): Max seconds to wait for planner. Default: 300.

        Returns:
            Optional[List[str]]: List of actions if plan is found, None otherwise.
        """
        # Compose command based on expected planner CLI
        # Example with FastDownward:
        # --search "astar(lmcut())" --plan-file temp_plan.txt domain.pddl problem.pddl
        cmd = [self.planner_path,
               '--search', 'astarlmcut()',
               '--plan-file', self._plan_filename,
               domain_filepath,
               problem_filepath]

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
            # Check exit code
            if result.returncode != 0:
                self.logger.info(f"Planner exited with code {result.returncode}. No plan found.")
                return None
            # Parse plan from output file
            plan = self._parse_plan(self._plan_filename)
            return plan
        except subprocess.TimeoutExpired:
            self.logger.warning("Planning timed out after {} seconds.".format(timeout))
            return None
        except Exception as e:
            self.logger.exception(f"Error during planning execution: {e}")
            return None

    def plan_exists(self, domain_filepath: str, problem_filepath: str, timeout: int = 300) -> bool:
        """
        Checks whether a plan exists for given domain and problem files.
        Args:
            domain_filepath (str)
            problem_filepath (str)
            timeout (int)

        Returns:
            bool: True if plan exists, False otherwise.
        """
        plan = self.run_planner(domain_filepath, problem_filepath, timeout)
        return plan is not None and len(plan) > 0

    def _parse_plan(self, plan_path: str) -> List[str]:
        """
        Parses the plan file to extract actions.
        Args:
            plan_path (str): Path to plan file generated by the planner.

        Returns:
            List[str]: List of action strings.
        """
        actions: List[str] = []
        if not os.path.exists(plan_path):
            return actions
        try:
            with open(plan_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    # Ignore comment lines or empty lines
                    if line and not line.startswith(';'):
                        actions.append(line)
            return actions
        except Exception as e:
            self.logger.exception(f"Error reading plan file: {e}")
            return []

